---
title: ""
---
<br>

# Maharrem Ayar
Department of Linguistics
  <br /> University of California Davis
 <br /> mrmayar [at] ucdavis dot edu
 <br /> Last Updated: March 2025

<br>

## Education

2023 - Cont. University of California, Davis, Linguistics Ph.D.

2017 - 2021 Boğaziçi University, Linguistics BA. 

\

## Publications in refereed journals\
  
Not yet.

## Presentations

2024 **Integration of B-Formats to Sign Language Classifier Constructions** *The Symposium on Language Research* Davis, CA, USA

2023 **My Sign App: Supporting Sign Language Acquisition of Deaf Children with Hearing Parents** *Student Conference on Linguistics.* İstanbul, Türkiye. (with Dilay Z. Karadöller)

2020 **A Proposition for Typology of Modality Markers in Sign Languages** *BUSTCEL* İstanbul, Türkiye

## Pop-Science

[Bilimin En Zor Problemi Serisi](https://medium.com/cogist/tagged/bilimin-en-zor-problemi)
<br />[Mentalese Muhabbet: İşaret Dili Biliş Hakkında Ne Söylüyor?](https://open.spotify.com/episode/5OokyTNJJvmBpCBadQ9hOx?si=XFu-rZeXRYO_f1CdYAzLVA&nd=1&dlsi=f02d09ff6ae54fdf)

## Teaching Experience

2025 Winter Quarter **Lin001Y - Introduction to Linguistics** *Teaching Assistant*, University of California, Davis

2024 Fall Quarter **Lin001Y - Introduction to Linguistics** *Teaching Assistant*, University of California, Davis

2024 Spring Quarter **Lin001Y - Introduction to Linguistics** *Teaching Assistant*, University of California, Davis

2024 Winter Quarter **Lin001Y - Introduction to Linguistics** *Teaching Assistant*, University of California, Davis

2023 Fall Quarter **Lin001 - Introduction to Linguistics** *Teaching Assistant*, University of California, Davis

## Experience

2023 - Cont. **Project Manager** *Max Planck Institute for Psycholinguistics*

2022 - 2023 **Project Manager** *SRCD Small Grants Program for Early Career Scholars 2022: My Sign App*

2020 - 2021 **Project Assistant** *TADNET - EU Endangered Languages Network*

2019 - 2020 **Project Assistant** *Boğaziçi University Research Fund #14458*
