project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Maharrem Ayar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
format:
  html:
    theme: darkly
    


